name: dosis_literaria
description: dosis diaria de literatura.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  settings_ui: ^0.6.0
  provider: ^5.0.0
  #google_sign_in: ^5.0.1
  sign_button: ^1.0.1
  flutter_login: ^1.1.0

#firebase
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1

#decoration
  font_awesome_flutter: ^9.0.0
  transformer_page_view: ^0.1.6
  another_flushbar: ^1.10.17
  flutter_group_sliver: ^0.0.2
  simple_animations: ^3.0.3
  like_button: ^2.0.2
  #google_mobile_ads: ^0.12.1

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  ## JSON
  json_annotation: ^4.0.1

  ## HTTP
  http: ^0.13.1

dev_dependencies:

  flutter_test:
    sdk: flutter
  #integration_test:
  #  sdk: flutter
  #flutter_launcher_icons: ^0.8.0

  ## JSON
  build_runner: ^1.12.2
  json_serializable: ^4.1.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"


flutter:
  
  uses-material-design: true
  assets:
    - assets/
    - assets/img/

  fonts:
    - family: Literata
      fonts:
        - asset: fonts/Literata-Regular.ttf
        - asset: fonts/Literata-Bold.ttf
        - asset: fonts/Literata-Medium.ttf
          
  
